channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=22.3.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.0
  - enum34==1.1.10
  - numpy==1.26.2
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.6.0
  - scipy==1.11.4
name: mlflow-env
